// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package account

// Injectors from wire.go:

func InitializeAccount() (routes, error) {
	repositoryImpl := NewRepository()
	accountServiceImpl := newService(repositoryImpl)
	accountController := newController(accountServiceImpl)
	middleware := NewMiddleware()
	accountRoutes := newRoutes(accountController, middleware)
	return accountRoutes, nil
}
