// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package account

// Injectors from wire.go:

func InitializeAccount() (routes, error) {
	accountRepositoryImpl := newRepository()
	accountServiceImpl := newService(accountRepositoryImpl)
	accountController := newController(accountServiceImpl)
	accountMiddleware := newMiddleware()
	accountRoutes := newRoutes(accountController, accountMiddleware)
	return accountRoutes, nil
}
