// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package files

import (
	"lending-service/account"
)

// Injectors from wire.go:

func InitializeRoutes() (routes, error) {
	repositoryImpl := NewRepository()
	filesServiceImpl := newService(repositoryImpl)
	filesController := newController(filesServiceImpl)
	middleware := account.NewMiddleware()
	filesRoutes := newRoutes(filesController, middleware)
	return filesRoutes, nil
}
