// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package loan

import (
	"lending-service/account"
)

// Injectors from wire.go:

func InitializeLoan() (routes, error) {
	loanRepositoryImpl := newRepository()
	loanServiceImpl := newService(loanRepositoryImpl)
	loanController := newController(loanServiceImpl)
	middleware := account.NewMiddleware()
	loanRoutes := newRoutes(loanController, middleware)
	return loanRoutes, nil
}
