// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package loan

import (
	"lending-service/account"
	"lending-service/config/database"
)

// Injectors from wire.go:

func InitializeLoanWithPostgres() (routes, error) {
	db := database.InitPostgreOrm()
	repositoryPostgresImpl := NewPostgresRepository(db)
	accountRepositoryPostgresImpl := account.NewPostgresRepository(db)
	loanServiceImpl := newService(repositoryPostgresImpl, accountRepositoryPostgresImpl)
	loanController := newController(loanServiceImpl)
	middleware := account.NewMiddleware()
	loanRoutes := newRoutes(loanController, middleware)
	return loanRoutes, nil
}

func InitializeLoanWithMysql() (routes, error) {
	db := database.InitMysql()
	repositoryMysqlImpl := NewMysqlRepository(db)
	accountRepositoryMysqlImpl := account.NewMysqlRepository(db)
	loanServiceImpl := newService(repositoryMysqlImpl, accountRepositoryMysqlImpl)
	loanController := newController(loanServiceImpl)
	middleware := account.NewMiddleware()
	loanRoutes := newRoutes(loanController, middleware)
	return loanRoutes, nil
}
